/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 chill_cat.glb 
Author: Shix (https://sketchfab.com/bel.ismail)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/chill-cat-3c46aadb77f644c8851dc935b14d93e9
Title: Chill Cat
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/chill_cat.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            geometry={nodes.defaultMaterial.geometry}
            material={materials["1001"]}
          />
          <mesh
            geometry={nodes.defaultMaterial_1.geometry}
            material={materials["1001"]}
          />
          <mesh
            geometry={nodes.defaultMaterial_2.geometry}
            material={materials["1001"]}
          />
          <mesh
            geometry={nodes.defaultMaterial_3.geometry}
            material={materials["1001"]}
          />
          <mesh
            geometry={nodes.defaultMaterial_4.geometry}
            material={materials["1001"]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/chill_cat.glb");
