# Generated by Django 5.0.2 on 2024-03-07 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudyNotes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EachSubjectNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notesTitle', models.CharField(blank=True, default='Un-Titled', max_length=255, null=True)),
                ('notesAre', models.TextField()),
                ('EachSubjectNotesIdentifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudyNotes.studynotes')),
            ],
        ),
    ]
