# Generated by Django 5.0.2 on 2024-03-03 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personal_Diary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldiarynotes',
            name='title',
            field=models.CharField(blank=True, default='Un-Titled', max_length=255, null=True),
        ),
    ]
