# Generated by Django 5.0.2 on 2024-03-04 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personal_Diary', '0003_alter_personaldiarynotes_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldiarynotes',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
