# Generated by Django 5.0.2 on 2024-03-05 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personal_Diary', '0004_alter_personaldiarynotes_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldiarynotes',
            name='body',
            field=models.TextField(blank=True, default='Please write Your Diary 😉', null=True),
        ),
    ]
