/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 2.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/2.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plane012.geometry} material={materials['Material.004']} position={[-1.909, 23.253, 2.649]} rotation={[-0.147, 0.116, 0.197]} scale={1.03} />
      <mesh geometry={nodes.Plane013.geometry} material={materials.Material} position={[-0.924, 25.166, 1.99]} rotation={[-0.147, 0.116, 0.482]} scale={1.03} />
      <mesh geometry={nodes.Plane014.geometry} material={materials['Material.008']} position={[-0.55, 26.235, 1.634]} rotation={[-0.147, 0.116, 0.609]} scale={1.03} />
      <group position={[-0.536, 28.877, 9.189]} rotation={[0.423, -0.49, -0.294]} scale={11.869}>
        <mesh geometry={nodes.Circle006.geometry} material={materials['Material.026']} />
        <mesh geometry={nodes.Circle006_1.geometry} material={materials['Material.025']} />
        <mesh geometry={nodes.Circle006_2.geometry} material={materials['Material.025']} />
        <mesh geometry={nodes.Circle006_3.geometry} material={materials['Material.026']} />
        <mesh geometry={nodes.Circle006_4.geometry} material={materials['Material.022']} />
      </group>
      <mesh geometry={nodes.NurbsPath010.geometry} material={materials['Material.022']} position={[-1.909, 23.253, 2.649]} rotation={[0, 0.095, 0]} />
    </group>
  )
}

useGLTF.preload('/2.gltf')
