/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 sketchfab_2018_07_19_11_54_00.glb 
Author: tailsluver29 (https://sketchfab.com/tailsluver28)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sketchfab-2018-07-19-11-54-00-1c1e37a687f24692ae308b16e8f888c3
Title: Sketchfab_2018_07_19_11_54_00
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/sketchfab_2018_07_19_11_54_00.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="Root">
            <group name="Pen_ref">
              <group name="Cylinder004" position={[0, 0, -0.238]} scale={0.21}>
                <mesh name="Cylinder004_0" geometry={nodes.Cylinder004_0.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder002">
                <mesh name="Cylinder002_0" geometry={nodes.Cylinder002_0.geometry} material={materials['Material.001']} />
              </group>
              <mesh name="Pen_ref_0" geometry={nodes.Pen_ref_0.geometry} material={materials['Material.001']} />
              <mesh name="Pen_ref_1" geometry={nodes.Pen_ref_1.geometry} material={materials['Material.002']} />
              <mesh name="Pen_ref_2" geometry={nodes.Pen_ref_2.geometry} material={materials['Material.004']} />
            </group>
            <group name="Armature">
              <primitive object={nodes.Armature_rootJoint} />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/sketchfab_2018_07_19_11_54_00.glb')
