/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 studygirlchallenge.glb 
Author: demidevil13 (https://sketchfab.com/demidevil13)
License: CC-BY-NC-ND-4.0 (http://creativecommons.org/licenses/by-nc-nd/4.0/)
Source: https://sketchfab.com/3d-models/studygirlchallenge-5b4cf5091ab142ada28b3f024d5c14b0
Title: #StudyGirlChallenge
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/studygirlchallenge.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Plane007_101" position={[-5.668, 8.976, 1.334]}>
                <mesh name="Object_147" geometry={nodes.Object_147.geometry} material={materials.materialAll} />
              </group>
              <group name="Cylinder015_0" position={[-0.182, -0.595, -0.502]} scale={[0.151, 0.874, 0.151]}>
                <mesh name="Object_4" geometry={nodes.Object_4.geometry} material={materials.materialAll} />
              </group>
              <group name="Cylinder016_1" position={[-0.103, 0.471, 1.086]} rotation={[-0.496, -1.506, -0.274]} scale={1.147}>
                <mesh name="Object_6" geometry={nodes.Object_6.geometry} material={materials.materialAll} />
              </group>
              <group name="Cube010_2" position={[-4.568, 4.995, 5.091]} rotation={[-Math.PI, 0, -Math.PI]}>
                <mesh name="Object_8" geometry={nodes.Object_8.geometry} material={materials.materialAll} />
              </group>
              <group name="Cylinder017_3" position={[-1.898, 1.743, 2.863]} scale={0.21}>
                <mesh name="Object_10" geometry={nodes.Object_10.geometry} material={materials.materialAll} />
              </group>
              <group name="Plane_4" position={[-1.636, 1.795, 1.548]} rotation={[0, 0.528, 0]} scale={0.071}>
                <mesh name="Object_12" geometry={nodes.Object_12.geometry} material={materials.materialAll} />
              </group>
              <group name="Armature002_10" position={[-4.802, 2.326, 1.771]} rotation={[-1.068, 0.793, -0.924]} scale={0.578}>
                <group name="GLTF_created_0">
                  <primitive object={nodes.GLTF_created_0_rootJoint} />
                  <group name="Cylinder_9" />
                  <skinnedMesh name="Object_17" geometry={nodes.Object_17.geometry} material={materials.materialAll} skeleton={nodes.Object_17.skeleton} />
                </group>
              </group>
              <group name="Plane002_13" position={[-0.182, 1.265, -1.261]} rotation={[1.457, -0.041, -0.105]}>
                <mesh name="Object_23" geometry={nodes.Object_23.geometry} material={materials.materialAll} />
              </group>
              <group name="Cube001_14" position={[-0.28, 1.451, 1.074]} rotation={[0, 0, -Math.PI]} scale={[-2.839, 0.087, 1.419]}>
                <mesh name="Object_25" geometry={nodes.Object_25.geometry} material={materials.materialAll} />
              </group>
              <group name="Armature_76" position={[-0.151, 0.806, -0.255]} rotation={[-0.264, -0.018, -0.023]}>
                <group name="GLTF_created_1">
                  <primitive object={nodes.GLTF_created_1_rootJoint} />
                  <group name="girl_68" />
                  <group name="girl001_69" />
                  <group name="girl002_70" />
                  <group name="girl003_71" />
                  <group name="girl004_72" />
                  <group name="girl005_73" />
                  <group name="girl006_74" />
                  <group name="girl007_75" />
                  <skinnedMesh name="Object_30" geometry={nodes.Object_30.geometry} material={materials.materialAll} skeleton={nodes.Object_30.skeleton} />
                  <skinnedMesh name="Object_32" geometry={nodes.Object_32.geometry} material={materials.materialAll} skeleton={nodes.Object_32.skeleton} />
                  <skinnedMesh name="Object_34" geometry={nodes.Object_34.geometry} material={materials.materialAll} skeleton={nodes.Object_34.skeleton} />
                  <skinnedMesh name="Object_36" geometry={nodes.Object_36.geometry} material={materials.materialAll} skeleton={nodes.Object_36.skeleton} />
                  <skinnedMesh name="Object_38" geometry={nodes.Object_38.geometry} material={materials.materialAll} skeleton={nodes.Object_38.skeleton} />
                  <skinnedMesh name="Object_40" geometry={nodes.Object_40.geometry} material={materials.materialAll} skeleton={nodes.Object_40.skeleton} />
                  <skinnedMesh name="Object_42" geometry={nodes.Object_42.geometry} material={materials.materialAll} skeleton={nodes.Object_42.skeleton} />
                  <skinnedMesh name="Object_44" geometry={nodes.Object_44.geometry} material={materials.materialAll} skeleton={nodes.Object_44.skeleton} />
                </group>
              </group>
              <group name="Cylinder001_78" position={[-1.659, 1.917, 2.318]}>
                <mesh name="Object_100" geometry={nodes.Object_100.geometry} material={materials.materialAll} />
              </group>
              <group name="Cube002_79" position={[-2.225, 1.622, 1.406]} rotation={[0, 0.24, 0]}>
                <mesh name="Object_102" geometry={nodes.Object_102.geometry} material={materials.materialAll} />
              </group>
              <group name="Cube003_80" position={[-2.225, 1.795, 1.406]} rotation={[0, 0.528, 0]}>
                <mesh name="Object_104" geometry={nodes.Object_104.geometry} material={materials.materialAll} />
              </group>
              <group name="Cube006_81" position={[-4.417, 2.103, -4.306]} scale={[1, 0.917, 1]}>
                <mesh name="Object_106" geometry={nodes.Object_106.geometry} material={materials.materialAll} />
              </group>
              <group name="Cube007_82" position={[-5.055, 4.439, 5.089]} scale={[0.677, 0.07, 1.642]}>
                <mesh name="Object_108" geometry={nodes.Object_108.geometry} material={materials.materialAll} />
              </group>
              <group name="Sphere_83" position={[-0.769, 4.244, 2.177]} scale={0.18}>
                <mesh name="Object_110" geometry={nodes.Object_110.geometry} material={materials.materialAll} />
              </group>
              <group name="Cylinder004_84" position={[-2.475, 2.147, 2.733]} rotation={[-0.48, 0.244, 0.394]}>
                <mesh name="Object_112" geometry={nodes.Object_112.geometry} material={materials.materialAll} />
              </group>
              <group name="Cylinder005_85" position={[-2.296, 2.147, 2.744]} rotation={[-0.219, 0.195, -0.48]} scale={[1, 1.21, 1]}>
                <mesh name="Object_114" geometry={nodes.Object_114.geometry} material={materials.materialAll} />
              </group>
              <group name="Cylinder007_86" position={[-2.556, 2.09, 2.996]} rotation={[0.023, 0.381, 0.431]} scale={[1, 1.21, 1]}>
                <mesh name="Object_116" geometry={nodes.Object_116.geometry} material={materials.materialAll} />
              </group>
              <group name="Cylinder008_87" position={[-2.293, 2.17, 3.108]} rotation={[0.682, -0.103, -0.231]} scale={[1, 1.21, 1]}>
                <mesh name="Object_118" geometry={nodes.Object_118.geometry} material={materials.materialAll} />
              </group>
              <group name="Plane005_88" position={[0, -2.11, 0]}>
                <mesh name="Object_120" geometry={nodes.Object_120.geometry} material={materials.materialAll} />
                <mesh name="Object_121" geometry={nodes.Object_121.geometry} material={materials.Material} />
              </group>
              <group name="Cylinder006_89" position={[-2.529, 2.23, 3.525]}>
                <mesh name="Object_123" geometry={nodes.Object_123.geometry} material={materials.materialAll} />
              </group>
              <group name="Cube018_90" position={[-3.622, 2.474, 3.629]} rotation={[0, 0.688, 0]}>
                <mesh name="Object_125" geometry={nodes.Object_125.geometry} material={materials.materialAll} />
              </group>
              <group name="Plane006_91" position={[2.431, 2.296, 2.072]} rotation={[0.129, -0.143, -1.705]}>
                <mesh name="Object_127" geometry={nodes.Object_127.geometry} material={materials.materialAll} />
              </group>
              <group name="Cylinder009_92" position={[2.364, 2.033, 2.184]} rotation={[0.564, 0.426, -0.354]}>
                <mesh name="Object_129" geometry={nodes.Object_129.geometry} material={materials.materialAll} />
              </group>
              <group name="Cylinder010_93" position={[2.364, 2.029, 1.8]} rotation={[1.772, 1.295, 0.901]} scale={[1, 1.21, 1]}>
                <mesh name="Object_131" geometry={nodes.Object_131.geometry} material={materials.materialAll} />
              </group>
              <group name="Cylinder011_94" position={[2.298, 2.066, 1.919]} rotation={[-0.282, -0.018, -0.172]}>
                <mesh name="Object_133" geometry={nodes.Object_133.geometry} material={materials.materialAll} />
              </group>
              <group name="Cylinder012_95" position={[2.297, 1.744, 1.992]} scale={0.211}>
                <mesh name="Object_135" geometry={nodes.Object_135.geometry} material={materials.materialAll} />
              </group>
              <group name="Cylinder013_96" position={[-2.447, 2.967, 3.4]} rotation={[-0.108, 0.036, -0.283]} scale={0.606}>
                <mesh name="Object_137" geometry={nodes.Object_137.geometry} material={materials.materialAll} />
              </group>
              <group name="Cylinder014_97" position={[-2.601, 2.889, 3.517]} rotation={[0.181, 0.33, 0.094]} scale={[1, 1.21, 1]}>
                <mesh name="Object_139" geometry={nodes.Object_139.geometry} material={materials.materialAll} />
              </group>
              <group name="Plane008_98" position={[-1.712, 2.55, 2.28]} rotation={[1.031, 0.51, 0.073]} scale={0.061}>
                <mesh name="Object_141" geometry={nodes.Object_141.geometry} material={materials.materialAll} />
              </group>
              <group name="Plane017_99" position={[-1.348, 4.192, 3.118]} rotation={[0.575, -0.564, 0.302]} scale={0.208}>
                <mesh name="Object_143" geometry={nodes.Object_143.geometry} material={materials.materialAll} />
              </group>
              <group name="Plane001_100" position={[0.209, 1.549, 0.863]} rotation={[0, 0.125, 0]}>
                <mesh name="Object_145" geometry={nodes.Object_145.geometry} material={materials.materialAll} />
              </group>
              <group name="Cube004_102" position={[-2.225, 1.947, 1.406]} rotation={[Math.PI, -1.231, Math.PI]} scale={[1, 0.754, 1]}>
                <mesh name="Object_149" geometry={nodes.Object_149.geometry} material={materials.materialAll} />
              </group>
              <group name="Cube005_103" position={[0.282, 1.57, 2.661]} rotation={[0, -0.416, 0]}>
                <mesh name="Object_151" geometry={nodes.Object_151.geometry} material={materials.materialAll} />
              </group>
              <group name="Cylinder003_104" position={[-2.403, 1.827, 2.913]} scale={0.757}>
                <mesh name="Object_153" geometry={nodes.Object_153.geometry} material={materials.materialAll} />
              </group>
              <group name="Plane003_105" position={[-4.319, 4.545, -3.083]} rotation={[0, 0.202, -Math.PI / 2]}>
                <mesh name="Object_155" geometry={nodes.Object_155.geometry} material={materials.materialAll} />
              </group>
              <group name="Plane004_106" position={[-5.327, 5.357, -2.927]} rotation={[0, 0, -Math.PI / 2]}>
                <mesh name="Object_157" geometry={nodes.Object_157.geometry} material={materials.materialAll} />
              </group>
              <group name="Plane018_107" position={[0.577, 1.54, 1.155]} rotation={[0, 0.568, 0]}>
                <mesh name="Object_159" geometry={nodes.Object_159.geometry} material={materials.materialAll} />
              </group>
              <group name="Plane019_108" position={[0.312, 1.538, 1.356]} rotation={[0, -0.125, 0]}>
                <mesh name="Object_161" geometry={nodes.Object_161.geometry} material={materials.materialAll} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/studygirlchallenge.glb')
